name: readreels
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '^3.7.0' # Обновил формат, чтобы соответствовать современным рекомендациям

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  image_picker: ^1.2.0
  go_router: ^17.0.0
  google_fonts: ^6.3.0
  provider: ^6.1.5
  shared_preferences: ^2.5.2
  smooth_page_indicator: ^1.2.1
  flutter_svg: 2.0.17
  cached_network_image: 3.4.1
  path_provider: 2.1.5
  pinput: 6.0.1
  flutter_carousel_slider: ^1.1.0
  onesignal_flutter: ^5.3.4
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.5.0
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/logo.svg
    - assets/icons/like.svg
    - assets/icons/settings.svg
    - assets/icons/search.svg
    - assets/icons/comment.svg
    - assets/icons/options.svg
