name: readreels
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '^3.7.0' # Обновил формат, чтобы соответствовать современным рекомендациям

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  image_picker: ^1.2.0
  go_router: ^17.0.0
  google_fonts: ^6.3.0
  provider: ^6.1.5
  shared_preferences: ^2.5.2
  smooth_page_indicator: ^1.2.1
  flutter_svg: 2.0.17
  cached_network_image: 3.4.1
  path_provider: 2.1.5
  pinput: 6.0.1
  connectivity_plus: 6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/logo.svg
    - assets/icons/like.svg
    - assets/icons/settings.svg
    - assets/icons/comment.svg
    - assets/icons/options.svg
